config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  resources :group, only: [:index, :new, :create] do
    resources :entities, only: [:index, :new, :create]
  end
  root to: 'group#index'

  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    return unless user.present?

    can :manage, Group, author: user
    can :manage, Entity, author: user
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_many :entities
  has_many :groups, through: :entities

  validates :name, presence: true, length: { in: 4..250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_many :entities
  has_many :entities, through: :entities

  validates :name, presence: true, length: { in: 4..250 }
  validates :icon, presence: true, length: { in: 4..250 }
  # icon must be a valid image.
  validates :icon,
            format: { with: /\.(gif|jpg|png|ico|jpeg)\Z/i,
                      message: 'must be a URL for GIF, JPG, PNG, ICO or Jpeg image.' }
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: :author_id
  has_many :groups, foreign_key: :author_id

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_devise_permitted_parameters, if: :devise_controller?

  protected

  def update_devise_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  before_action :set_entity, only: [:edit, :update, :destroy]

  def index
    @entities = @group.entities
  end

  def new
    @entity = @group.entities.new
  end

  def create
    @entity = @group.entities.new(entity_params)
    if @entity.save
      flash[:notice] = 'Transaction created successfully'
      redirect_to group_entities_path(@group)
    else
      flash.now[:alert] = 'Transaction creation failed'
      render action: 'new'
    end
      end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def set_entity
    @entity = @group.entities.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @groups = current_user.groups
    else
      render 'users/splash'
    end
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @user = current_user
    @group = @user.groups.create(group_params)
    if @group.save
      flash[:notice] = 'New category created successfully'
      redirect_to group_index_path
    else
      flash.now[:alert] = 'Category creation failed'
      render action: 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/entities/index.html.erb
<div class="min_nav">
  <%= link_to "", group_index_path, class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">Transactions</h3>
</div>
<div class="card mb-2">
  <div class="card-body d-flex justify-content-between align-items-center">
    <%= image_tag @group.icon || "http://localhost:3000/users/sign_up.jpg", class: 'card_icon' %>
    <div>
      <p class="fw-semibold"><%= @group.name %></p>
      <p class="fw-light"><%= l @group.created_at, format: :long %></p>
    </div>
    <p class="fw-bolder">
      $<%= @group.entities.sum(&:amount) %>
    </p>
  </div>
</div>
<% if @entities.count > 0 %>
  <% @entities.order(created_at: :desc).limit(4).each do |entity| %>
    <div class="card mb-2">
      <div class="card-body d-flex justify-content-between align-items-center">
        <div>
          <p class="fw-semibold"><%= entity.name %></p>
          <p class="fw-light"><%= l entity.created_at, format: :long %></p>
        </div>
        <p class="fw-bolder">
          $<%= entity.amount %>
        </p>
      </div>
    </div>
  <% end %>
<% else %>
  <p>You have no Transactions</p>
<% end %>
<%= link_to 'Add Transaction', new_group_entity_path(@group), class: "btn btn-primary fixed-bottom" %>

app/views/entities/new.html.erb
<div class="min_nav">
  <%= link_to "", entities_path(@group), class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">New Transaction</h3>
</div>
<%= form_with model: @entity, url: entities_path, method: :post, data: { turbo: false } do |form| %>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Transaction name' %>
  </div>
  <div class="mb-3">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: 'form-control', placeholder: 12, type: "number", step: ".01" %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/group/index.html.erb
<h3 class="mb-3">Categories</h3>

<% if @groups.count > 0 %>
  <% @groups.each do |group| %>
    <%= link_to group_entities(group), class: "card mb-2" do %>
      <div class="card-body d-flex justify-content-between align-items-center">
        <%= image_tag group.icon || "http://localhost:3000/users/sign_up.jpg", class: 'card_icon' %>
        <div>
          <p class="fwsemibold">Created_by : <%= current_user.name %></p>
          <p class="fw-semibold">Category_ name : <%= group.name %></p>
        </div>
        <p class="fw-bolder">
          <%= group.entities.sum(&:amount) %>
        </p>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>You have no categories and new to continue</p>
<% end %>
<%= link_to 'Add Category', new_group_path, class: "btn btn-primary fixed-bottom" %>

app/views/group/new.html.erb
<div class="min_nav">
  <%# display all errors %>
  <% if @group.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
  <%= link_to "", group_index_path, class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">Categories</h3>
</div>
<%= form_with model: @group, url: group_index_path, method: :post, data: { turbo: false } do |form| %>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Category name' %>
  </div>
  <div class="mb-3">
    <%= form.label :icon %>
    <%= form.url_field :icon, class: 'form-control', placeholder: 'Icon url' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Create category', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <script src="https://kit.fontawesome.com/bd217347c8.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div class="container main-body">
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mt-4" role="alert">
    <%= notice %>
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= alert %>
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-light">
  <div class="container-fluid">
    <h3 class="navbar-brand">App_Budget</h3>
    <button class="navbar-toggler btn btn-outline-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fa fa-bars"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>          
          <li class="nav-item"> 
            <span class="nav-link me-5 text-light"><i class="fa fa-user me-2"></i><%= current_user.name %></span>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-sm btn-outline-warning' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_session_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-light' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/splash.html.erb
<div class="d-flex flex-column justify-content-center align-items-center mt-4">
  <h1 class="h1 text-primary mt-4">App_Budget</h1>

  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.pexels.com/photos/5849581/pexels-photo-5849581.jpeg?auto=compress&cs=tinysrgb&w=400" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.pexels.com/photos/5849596/pexels-photo-5849596.jpeg?auto=compress&cs=tinysrgb&w=400" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.pexels.com/photos/5849577/pexels-photo-5849577.jpeg?auto=compress&cs=tinysrgb&w=400" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <%= link_to "Sign In", new_user_session_path, class: 'btn-outline-primary mt-4' %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary mt-2' %>
  
</div>